name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        # [주의] A와 S는 반드시 대문자여야 합니다!
        uses: ArtemSerebrennkov/buildozer-action@v1
        with:
          buildozer_version: master
          python_version: 3.11

      - name: Upload APK
        # 최신 v4 버전 (필수)
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
